import type { SearchIntent } from '../../contracts/enums';
import type { ClusterRuleset } from './ruleset';
import type { ConstraintNode, ConstraintViolation } from './constraints';
import { forbiddenEdgeViolations } from './constraints';
import { cosineSimilarity, jaccardSerpOverlap, intentCompatibility } from './similarity';

// NOTE: domain/graph.ts (page hierarchy) is a different module. This is the
// clustering similarity graph. Pure: no IO, no env, no Date.now, no Math.random.

export interface KeywordNode extends ConstraintNode {
  keywordId: string;
  normalizedKeyword: string;
  tokens: readonly string[];
  coreKeyword: string | null;
  vector: ArrayLike<number> | null;
  serpUrls: ReadonlySet<string> | null;
  relevance: number | null;
  volume: number | null;
}

export interface GraphEdge {
  a: string; // keywordId, a < b lexicographically
  b: string;
  score: number;
  components: { semantic: number | null; serpJaccard: number | null; intent: number | null };
  weightsUsed: { semantic: number; serpOverlap: number; intent: number };
  violations: ConstraintViolation[]; // non-empty => forbidden (kept for reporting)
}

export interface GraphStats {
  candidatePairs: number; // unique candidate pairs generated by blocking, pre-cap
  scoredEdges: number; // candidate pairs (post-cap) with at least one signal, so an edge exists
  forbiddenEdges: number; // scored edges that carry >=1 constraint violation
  blockedByCap: number; // candidate pairs dropped by ruleset.blocking.maxCandidatePairs
}

const PAIR_SEP = '\u0000';

function round6(x: number): number {
  return Math.round(x * 1e6) / 1e6;
}

export interface ScoreResult {
  score: number;
  weightsUsed: { semantic: number; serpOverlap: number; intent: number };
}

// Renormalizes the base edge weights over the present (non-null) components and
// returns the weighted score. Returns null when every component is missing (no
// edge). Score and weights are rounded to 6dp so hash comparisons are stable
// across float noise. Exported so refine_clusters (Task 12) scores its
// cluster-boundary edges with the exact same weighting/renormalization/rounding
// stage 10 uses for keyword-pair edges.
export function scoreEdge(
  semantic: number | null,
  serpJaccard: number | null,
  intent: number | null,
  ruleset: ClusterRuleset,
): ScoreResult | null {
  const base = ruleset.edgeWeights;
  const present: { key: 'semantic' | 'serpOverlap' | 'intent'; value: number; weight: number }[] = [];
  if (semantic !== null) present.push({ key: 'semantic', value: semantic, weight: base.semantic });
  if (serpJaccard !== null) present.push({ key: 'serpOverlap', value: serpJaccard, weight: base.serpOverlap });
  if (intent !== null) present.push({ key: 'intent', value: intent, weight: base.intent });
  if (present.length === 0) return null;

  const sumWeight = present.reduce((s, p) => s + p.weight, 0);
  const weightsUsed = { semantic: 0, serpOverlap: 0, intent: 0 };
  let score = 0;
  for (const p of present) {
    const w = ruleset.weightRenormalization && sumWeight > 0 ? p.weight / sumWeight : p.weight;
    weightsUsed[p.key] = round6(w);
    score += p.value * w;
  }
  return { score: round6(score), weightsUsed };
}

// Whether a scored, violation-free edge is allowed to drive a MERGE decision
// (cluster assembly in clusters.ts, auto-merge eligibility in refine.ts).
// A pair with measured SERP overlap qualifies on the combined edgeThreshold
// alone. A pair WITHOUT measured SERP overlap is semantic-only after weight
// renormalization (an effective bar of cosine >= ~0.55, below the measured
// cross-service median; see the cluster-v2 note in ruleset.ts), so it must
// additionally clear clusters.semanticOnlyMergeFloor. A pair with neither
// SERP overlap nor a cosine (vectors missing) can never merge on intent
// alone.
export function edgeEligibleForMerge(
  edge: Pick<GraphEdge, 'score' | 'components'>,
  ruleset: ClusterRuleset,
): boolean {
  if (edge.score < ruleset.edgeThreshold) return false;
  if (edge.components.serpJaccard !== null) return true;
  return (
    edge.components.semantic !== null &&
    edge.components.semantic >= ruleset.clusters.semanticOnlyMergeFloor
  );
}

export function buildKeywordSimilarityGraph(input: {
  nodes: readonly KeywordNode[];
  ruleset: ClusterRuleset;
}): { edges: GraphEdge[]; stats: GraphStats } {
  const { nodes, ruleset } = input;
  const byId = new Map<string, KeywordNode>();
  for (const n of nodes) byId.set(n.keywordId, n);

  // Blocking: bucket node ids by each shared dimension. A pair is a candidate iff
  // it co-occurs in at least one bucket (same coreKeyword, a serviceId, a
  // serviceAreaId, or a shared token).
  const buckets = new Map<string, Set<string>>();
  const addToBucket = (key: string, id: string) => {
    let set = buckets.get(key);
    if (!set) { set = new Set(); buckets.set(key, set); }
    set.add(id);
  };
  for (const n of nodes) {
    if (n.coreKeyword !== null) addToBucket(`core:${n.coreKeyword}`, n.keywordId);
    for (const sid of n.serviceIds) addToBucket(`svc:${sid}`, n.keywordId);
    for (const aid of n.serviceAreaIds) addToBucket(`area:${aid}`, n.keywordId);
    for (const tok of n.tokens) addToBucket(`tok:${tok}`, n.keywordId);
  }

  // Generate unique candidate pairs. Iterate bucket keys and member ids in
  // sorted order so generation is order-invariant.
  const candidateSet = new Set<string>();
  for (const bucketKey of [...buckets.keys()].sort()) {
    const ids = [...buckets.get(bucketKey)!].sort();
    for (let i = 0; i < ids.length; i++) {
      for (let j = i + 1; j < ids.length; j++) {
        candidateSet.add(`${ids[i]}${PAIR_SEP}${ids[j]}`);
      }
    }
  }

  const candidatePairs = candidateSet.size;
  const sortedPairKeys = [...candidateSet].sort();
  const cap = ruleset.blocking.maxCandidatePairs;
  const retained = sortedPairKeys.slice(0, cap);
  const blockedByCap = Math.max(0, candidatePairs - retained.length);

  const edges: GraphEdge[] = [];
  let scoredEdges = 0;
  let forbiddenEdges = 0;

  const low = ruleset.clusters.ambiguousBand.low;

  for (const pairKey of retained) {
    const sep = pairKey.indexOf(PAIR_SEP);
    const aId = pairKey.slice(0, sep);
    const bId = pairKey.slice(sep + 1);
    const a = byId.get(aId);
    const b = byId.get(bId);
    if (!a || !b) continue;

    const semantic = cosineSimilarity(a.vector, b.vector);
    const serpJaccard = jaccardSerpOverlap(a.serpUrls, b.serpUrls);
    const intent = intentCompatibility(a.intent, b.intent);

    const scored = scoreEdge(semantic, serpJaccard, intent, ruleset);
    if (scored === null) continue; // no signal at all, no edge

    scoredEdges++;
    const violations = forbiddenEdgeViolations(a, b);
    if (violations.length > 0) forbiddenEdges++;

    // Return threshold-passing edges, ambiguous-band edges (needed by refine),
    // and every forbidden edge (kept for reporting). Sub-band clean edges are
    // dropped. The band [low, high) union [high, inf) collapses to score >= low.
    if (scored.score >= low || violations.length > 0) {
      edges.push({
        a: aId,
        b: bId,
        score: scored.score,
        components: { semantic, serpJaccard, intent },
        weightsUsed: scored.weightsUsed,
        violations,
      });
    }
  }

  edges.sort((x, y) => (x.a < y.a ? -1 : x.a > y.a ? 1 : x.b < y.b ? -1 : x.b > y.b ? 1 : 0));

  return {
    edges,
    stats: { candidatePairs, scoredEdges, forbiddenEdges, blockedByCap },
  };
}
