import type { Env } from '../index';

// White-label export branding: logo (R2 object in TASK_ATTACHMENTS), brand
// color (hex), and brand name stored on the users row. Consumed by the SPA
// export engine to skin PDF/DOCX reports. The "Generated by DataWise SEO"
// footer attribution is rendered client-side and is not configurable here.

const json = (data: unknown, status = 200) =>
  new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json' } });

function generateId(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

const MAX_LOGO_BYTES = 1 * 1024 * 1024; // 1 MB
// No SVG: jsPDF cannot embed it in exported reports.
const ALLOWED_LOGO_MIME = /^image\/(png|jpeg|webp)$/i;
const HEX_COLOR_RE = /^#[0-9a-fA-F]{6}$/;
const MAX_BRAND_NAME_LENGTH = 60;

interface BrandingRow {
  branding_logo_key: string | null;
  branding_color: string | null;
  branding_name: string | null;
}

async function getBrandingRow(env: Env, userId: string): Promise<BrandingRow | null> {
  return env.DB.prepare(
    'SELECT branding_logo_key, branding_color, branding_name FROM users WHERE id = ?'
  )
    .bind(userId)
    .first<BrandingRow>();
}

// Attachment URLs are absolute, built from the request origin, matching how
// handleUploadTaskAttachment in site-audit.ts returns them.
function logoUrl(request: Request, key: string | null): string | null {
  if (!key) return null;
  const origin = new URL(request.url).origin;
  return `${origin}/api/attachments/${key}`;
}

function brandingResponse(request: Request, row: BrandingRow) {
  return {
    logo_url: logoUrl(request, row.branding_logo_key),
    brand_color: row.branding_color,
    brand_name: row.branding_name,
  };
}

// ---------- GET /api/branding ----------
export async function handleGetBranding(
  request: Request,
  env: Env,
  userId: string
): Promise<Response> {
  const row = await getBrandingRow(env, userId);
  if (!row) return json({ error: 'User not found' }, 404);
  return json(brandingResponse(request, row));
}

// ---------- POST /api/branding/logo ----------
// Multipart/form-data with a single "file" field. PNG, JPEG or WebP, 1 MB max.
// Replaces any previous logo and deletes the old R2 object.
export async function handleUploadBrandingLogo(
  request: Request,
  env: Env,
  userId: string
): Promise<Response> {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return json({ error: 'Expected multipart/form-data' }, 400);
  }
  const fileRaw = form.get('file');
  if (!fileRaw || typeof fileRaw === 'string') return json({ error: 'file field required' }, 400);
  const file = fileRaw as unknown as {
    size: number;
    type: string;
    name: string;
    stream: () => ReadableStream;
  };
  if (file.size === 0) return json({ error: 'Empty file' }, 400);
  if (file.size > MAX_LOGO_BYTES) return json({ error: 'Logo exceeds 1 MB limit' }, 413);

  const contentType = file.type || 'application/octet-stream';
  if (!ALLOWED_LOGO_MIME.test(contentType)) {
    return json({ error: `Unsupported file type: ${contentType}. Use PNG, JPG or WebP.` }, 415);
  }

  const row = await getBrandingRow(env, userId);
  if (!row) return json({ error: 'User not found' }, 404);
  const previousKey = row.branding_logo_key;

  const ext = contentType.split('/')[1]?.replace('jpeg', 'jpg') || 'bin';
  const key = `${userId}/branding/${generateId()}.${ext}`;

  await env.TASK_ATTACHMENTS.put(key, file.stream(), {
    httpMetadata: { contentType },
  });

  await env.DB.prepare(
    "UPDATE users SET branding_logo_key = ?, updated_at = datetime('now') WHERE id = ?"
  )
    .bind(key, userId)
    .run();

  if (previousKey) {
    await env.TASK_ATTACHMENTS.delete(previousKey);
  }

  return json(
    brandingResponse(request, { ...row, branding_logo_key: key }),
    201
  );
}

// ---------- PATCH /api/branding ----------
// Body: { brand_color?: string | null, brand_name?: string | null }.
// Explicit nulls clear a field; omitted fields are untouched.
export async function handleUpdateBranding(
  request: Request,
  env: Env,
  userId: string
): Promise<Response> {
  const body = (await request.json().catch(() => ({}))) as {
    brand_color?: string | null;
    brand_name?: string | null;
  };

  const sets: string[] = [];
  const values: unknown[] = [];

  if (body.brand_color !== undefined) {
    if (body.brand_color !== null) {
      if (typeof body.brand_color !== 'string' || !HEX_COLOR_RE.test(body.brand_color)) {
        return json({ error: 'brand_color must be a hex color like #005232' }, 400);
      }
    }
    sets.push('branding_color = ?');
    values.push(body.brand_color);
  }

  if (body.brand_name !== undefined) {
    if (body.brand_name !== null && typeof body.brand_name !== 'string') {
      return json({ error: 'brand_name must be a string or null' }, 400);
    }
    const trimmed = body.brand_name === null ? null : body.brand_name.trim().slice(0, MAX_BRAND_NAME_LENGTH);
    sets.push('branding_name = ?');
    values.push(trimmed || null);
  }

  if (sets.length === 0) return json({ error: 'Nothing to update' }, 400);

  sets.push("updated_at = datetime('now')");
  values.push(userId);

  await env.DB.prepare(`UPDATE users SET ${sets.join(', ')} WHERE id = ?`)
    .bind(...values)
    .run();

  const row = await getBrandingRow(env, userId);
  if (!row) return json({ error: 'User not found' }, 404);
  return json(brandingResponse(request, row));
}

// ---------- DELETE /api/branding/logo ----------
export async function handleDeleteBrandingLogo(
  env: Env,
  userId: string
): Promise<Response> {
  const row = await getBrandingRow(env, userId);
  if (!row) return json({ error: 'User not found' }, 404);

  if (row.branding_logo_key) {
    await env.TASK_ATTACHMENTS.delete(row.branding_logo_key);
    await env.DB.prepare(
      "UPDATE users SET branding_logo_key = NULL, updated_at = datetime('now') WHERE id = ?"
    )
      .bind(userId)
      .run();
  }

  return json({ success: true });
}
