// DataForSEO Locations and Languages
// Last updated: 2025-08-05

export interface LocationOption {
  value: number;
  label: string;
  countryCode: string;
}

export interface LanguageOption {
  value: string;
  label: string;
}

export const locationOptions: LocationOption[] = [
  { value: 2008, label: "Albania", countryCode: "AL" },
  { value: 2012, label: "Algeria", countryCode: "DZ" },
  { value: 2024, label: "Angola", countryCode: "AO" },
  { value: 2031, label: "Azerbaijan", countryCode: "AZ" },
  { value: 2032, label: "Argentina", countryCode: "AR" },
  { value: 2036, label: "Australia", countryCode: "AU" },
  { value: 2040, label: "Austria", countryCode: "AT" },
  { value: 2048, label: "Bahrain", countryCode: "BH" },
  { value: 2050, label: "Bangladesh", countryCode: "BD" },
  { value: 2051, label: "Armenia", countryCode: "AM" },
  { value: 2056, label: "Belgium", countryCode: "BE" },
  { value: 2068, label: "Bolivia", countryCode: "BO" },
  { value: 2070, label: "Bosnia and Herzegovina", countryCode: "BA" },
  { value: 2076, label: "Brazil", countryCode: "BR" },
  { value: 2100, label: "Bulgaria", countryCode: "BG" },
  { value: 2104, label: "Myanmar (Burma)", countryCode: "MM" },
  { value: 2116, label: "Cambodia", countryCode: "KH" },
  { value: 2120, label: "Cameroon", countryCode: "CM" },
  { value: 2124, label: "Canada", countryCode: "CA" },
  { value: 2144, label: "Sri Lanka", countryCode: "LK" },
  { value: 2152, label: "Chile", countryCode: "CL" },
  { value: 2158, label: "Taiwan", countryCode: "TW" },
  { value: 2170, label: "Colombia", countryCode: "CO" },
  { value: 2188, label: "Costa Rica", countryCode: "CR" },
  { value: 2191, label: "Croatia", countryCode: "HR" },
  { value: 2196, label: "Cyprus", countryCode: "CY" },
  { value: 2203, label: "Czechia", countryCode: "CZ" },
  { value: 2208, label: "Denmark", countryCode: "DK" },
  { value: 2218, label: "Ecuador", countryCode: "EC" },
  { value: 2222, label: "El Salvador", countryCode: "SV" },
  { value: 2233, label: "Estonia", countryCode: "EE" },
  { value: 2246, label: "Finland", countryCode: "FI" },
  { value: 2250, label: "France", countryCode: "FR" },
  { value: 2276, label: "Germany", countryCode: "DE" },
  { value: 2288, label: "Ghana", countryCode: "GH" },
  { value: 2300, label: "Greece", countryCode: "GR" },
  { value: 2320, label: "Guatemala", countryCode: "GT" },
  { value: 2344, label: "Hong Kong", countryCode: "HK" },
  { value: 2348, label: "Hungary", countryCode: "HU" },
  { value: 2356, label: "India", countryCode: "IN" },
  { value: 2360, label: "Indonesia", countryCode: "ID" },
  { value: 2372, label: "Ireland", countryCode: "IE" },
  { value: 2376, label: "Israel", countryCode: "IL" },
  { value: 2380, label: "Italy", countryCode: "IT" },
  { value: 2384, label: "Cote d'Ivoire", countryCode: "CI" },
  { value: 2392, label: "Japan", countryCode: "JP" },
  { value: 2398, label: "Kazakhstan", countryCode: "KZ" },
  { value: 2400, label: "Jordan", countryCode: "JO" },
  { value: 2404, label: "Kenya", countryCode: "KE" },
  { value: 2410, label: "South Korea", countryCode: "KR" },
  { value: 2428, label: "Latvia", countryCode: "LV" },
  { value: 2440, label: "Lithuania", countryCode: "LT" },
  { value: 2458, label: "Malaysia", countryCode: "MY" },
  { value: 2470, label: "Malta", countryCode: "MT" },
  { value: 2484, label: "Mexico", countryCode: "MX" },
  { value: 2492, label: "Monaco", countryCode: "MC" },
  { value: 2498, label: "Moldova", countryCode: "MD" },
  { value: 2504, label: "Morocco", countryCode: "MA" },
  { value: 2528, label: "Netherlands", countryCode: "NL" },
  { value: 2554, label: "New Zealand", countryCode: "NZ" },
  { value: 2558, label: "Nicaragua", countryCode: "NI" },
  { value: 2566, label: "Nigeria", countryCode: "NG" },
  { value: 2578, label: "Norway", countryCode: "NO" },
  { value: 2586, label: "Pakistan", countryCode: "PK" },
  { value: 2591, label: "Panama", countryCode: "PA" },
  { value: 2600, label: "Paraguay", countryCode: "PY" },
  { value: 2604, label: "Peru", countryCode: "PE" },
  { value: 2608, label: "Philippines", countryCode: "PH" },
  { value: 2616, label: "Poland", countryCode: "PL" },
  { value: 2620, label: "Portugal", countryCode: "PT" },
  { value: 2642, label: "Romania", countryCode: "RO" },
  { value: 2682, label: "Saudi Arabia", countryCode: "SA" },
  { value: 2686, label: "Senegal", countryCode: "SN" },
  { value: 2688, label: "Serbia", countryCode: "RS" },
  { value: 2702, label: "Singapore", countryCode: "SG" },
  { value: 2703, label: "Slovakia", countryCode: "SK" },
  { value: 2704, label: "Vietnam", countryCode: "VN" },
  { value: 2705, label: "Slovenia", countryCode: "SI" },
  { value: 2710, label: "South Africa", countryCode: "ZA" },
  { value: 2724, label: "Spain", countryCode: "ES" },
  { value: 2752, label: "Sweden", countryCode: "SE" },
  { value: 2756, label: "Switzerland", countryCode: "CH" },
  { value: 2764, label: "Thailand", countryCode: "TH" },
  { value: 2784, label: "United Arab Emirates", countryCode: "AE" },
  { value: 2788, label: "Tunisia", countryCode: "TN" },
  { value: 2792, label: "Turkiye", countryCode: "TR" },
  { value: 2804, label: "Ukraine", countryCode: "UA" },
  { value: 2807, label: "North Macedonia", countryCode: "MK" },
  { value: 2818, label: "Egypt", countryCode: "EG" },
  { value: 2826, label: "United Kingdom", countryCode: "GB" },
  { value: 2840, label: "United States", countryCode: "US" },
  { value: 2854, label: "Burkina Faso", countryCode: "BF" },
  { value: 2858, label: "Uruguay", countryCode: "UY" },
  { value: 2862, label: "Venezuela", countryCode: "VE" },
];

export const languageOptions: LanguageOption[] = [
  { value: "sq", label: "Albanian" },
  { value: "ar", label: "Arabic" },
  { value: "hy", label: "Armenian" },
  { value: "az", label: "Azeri" },
  { value: "bn", label: "Bengali" },
  { value: "bs", label: "Bosnian" },
  { value: "bg", label: "Bulgarian" },
  { value: "zh-CN", label: "Chinese (Simplified)" },
  { value: "zh-TW", label: "Chinese (Traditional)" },
  { value: "hr", label: "Croatian" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "nl", label: "Dutch" },
  { value: "en", label: "English" },
  { value: "et", label: "Estonian" },
  { value: "fi", label: "Finnish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "el", label: "Greek" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "hu", label: "Hungarian" },
  { value: "id", label: "Indonesian" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "lv", label: "Latvian" },
  { value: "lt", label: "Lithuanian" },
  { value: "mk", label: "Macedonian" },
  { value: "ms", label: "Malay" },
  { value: "nb", label: "Norwegian (Bokmål)" },
  { value: "pl", label: "Polish" },
  { value: "pt", label: "Portuguese" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "sr", label: "Serbian" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "es", label: "Spanish" },
  { value: "sv", label: "Swedish" },
  { value: "tl", label: "Tagalog" },
  { value: "th", label: "Thai" },
  { value: "tr", label: "Turkish" },
  { value: "uk", label: "Ukrainian" },
  { value: "ur", label: "Urdu" },
  { value: "vi", label: "Vietnamese" },
];
