export const BRAND = {
  primary: '#005232',
  primaryLight: '#0a7a4a',
  textDark: '#0f1f17',
  textMuted: '#5a6a62',
  bgMuted: '#f3f7f4',
  borderLight: '#dbe5e0',
  accentUp: '#0f8a4d',
  accentDown: '#c0392b',
  accentNeutral: '#6b7280',
} as const;

export const BRAND_RGB = {
  primary: [0, 82, 50] as [number, number, number],
  primaryLight: [10, 122, 74] as [number, number, number],
  textDark: [15, 31, 23] as [number, number, number],
  textMuted: [90, 106, 98] as [number, number, number],
  bgMuted: [243, 247, 244] as [number, number, number],
  borderLight: [219, 229, 224] as [number, number, number],
  accentUp: [15, 138, 77] as [number, number, number],
  accentDown: [192, 57, 43] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
} as const;

export const BRAND_NAME = 'DataWise SEO';
export const BRAND_URL = 'datawiseseo.com';
export const BRAND_FOOTER = (date: Date) =>
  `Generated by ${BRAND_NAME} · ${BRAND_URL} · ${date.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })}`;
