export const BRAND = {
  primary: '#005232',
  primaryLight: '#0a7a4a',
  textDark: '#0f1f17',
  textMuted: '#5a6a62',
  bgMuted: '#f3f7f4',
  borderLight: '#dbe5e0',
  accentUp: '#0f8a4d',
  accentDown: '#c0392b',
  accentNeutral: '#6b7280',
} as const;

export const BRAND_RGB = {
  primary: [0, 82, 50] as [number, number, number],
  primaryLight: [10, 122, 74] as [number, number, number],
  textDark: [15, 31, 23] as [number, number, number],
  textMuted: [90, 106, 98] as [number, number, number],
  bgMuted: [243, 247, 244] as [number, number, number],
  borderLight: [219, 229, 224] as [number, number, number],
  accentUp: [15, 138, 77] as [number, number, number],
  accentDown: [192, 57, 43] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
} as const;

export const BRAND_NAME = 'DataWise SEO';

type Rgb = [number, number, number];

export interface ExportPalette {
  /** Hex colors, same shape as BRAND. */
  hex: { [K in keyof typeof BRAND]: string };
  /** RGB tuples, same shape as BRAND_RGB. */
  rgb: { [K in keyof typeof BRAND_RGB]: Rgb };
  /**
   * True when the custom primary is too light to carry text or table
   * headers. Renderers then keep the default dark text/header colors and use
   * the custom color only for accent bars and fills.
   */
  isLight: boolean;
}

function hexToRgb(hex: string): Rgb {
  const clean = hex.replace('#', '');
  return [
    parseInt(clean.slice(0, 2), 16),
    parseInt(clean.slice(2, 4), 16),
    parseInt(clean.slice(4, 6), 16),
  ];
}

function rgbToHex([r, g, b]: Rgb): string {
  return '#' + [r, g, b].map((c) => c.toString(16).padStart(2, '0')).join('');
}

/** Lighten a color toward white by the given amount (0 to 1). */
function lighten(rgb: Rgb, amount: number): Rgb {
  return rgb.map((c) => Math.round(c + (255 - c) * amount)) as Rgb;
}

/** WCAG relative luminance, 0 (black) to 1 (white). */
export function relativeLuminance(hex: string): number {
  const [r, g, b] = hexToRgb(hex).map((c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/**
 * Build an export palette from a custom brand color. primary is the custom
 * color, primaryLight is the same color lightened ~25% toward white. All
 * other slots keep the DataWise defaults so neutral text, borders, and
 * up/down accents stay readable.
 */
export function derivePalette(hex: string): ExportPalette {
  const primaryRgb = hexToRgb(hex);
  const primaryLightRgb = lighten(primaryRgb, 0.25);
  return {
    hex: {
      ...BRAND,
      primary: hex.toLowerCase(),
      primaryLight: rgbToHex(primaryLightRgb),
    },
    rgb: {
      ...BRAND_RGB,
      primary: primaryRgb,
      primaryLight: primaryLightRgb,
    },
    isLight: relativeLuminance(hex) > 0.7,
  };
}
export const BRAND_URL = 'datawiseseo.com';
export const BRAND_FOOTER = (date: Date) =>
  `Generated by ${BRAND_NAME} · ${BRAND_URL} · ${date.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })}`;
